### ISSUE TITLE
Printability of website

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#395]
We should offer a specific css for media 'print' and then use them to show/hide what should be shown or hidden in printed documents

``` css
@media print {
  /* .visible-print  { display: inherit !important; }  */
  .hidden-print   { display: none !important; }
}
```

**update!** I commented .visible-print 

It's will be nice if a printing button will be shown somewhere in the page, so the users can get to use it
